# Generated by Django 5.1.6 on 2025-03-31 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authapp', '0008_alter_order_user_alter_shippingaddress_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('COD', 'Cash on Delivery'), ('UPI', 'UPI'), ('CARD', 'Cards')], default='COD', max_length=20),
        ),
    ]
