# Generated by Django 5.1.6 on 2025-03-31 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authapp', '0009_order_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='unique_order_id',
            field=models.CharField(default='ORDDEFAULT', editable=False, max_length=12, unique=True),
            preserve_default=False,
        ),
    ]
