# Generated by Django 5.1.6 on 2025-04-04 05:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authapp', '0013_contactus'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReturnOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('Defective Product', 'Defective Product'), ('Wrong Item Received', 'Wrong Item Received'), ('Better Price Available', 'Better Price Available'), ('No Longer Needed', 'No Longer Needed'), ('Other', 'Other')], max_length=255)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Completed', 'Completed')], default='Pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Authapp.order')),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Authapp.orderitem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Authapp.customuser')),
            ],
        ),
    ]
